#!/usr/bin/env ruby

ENV["RAILS_ENV"] = "production"
require_relative "../config/environment"

Proposal
  .all
  .map {|p| [p, Selection.find_all_by_proposal_id(p.id)]}
  .map {|k,v| [k.title, k.proposer.name, v.count] }
  .sort_by {|c| -c[2] }
  .each {|c| printf "%3d %25s: %s\n", c[2], c[1], c[0] }

